const $ = id => document.getElementById(id);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const short = (s,n=34) => String(s ?? '').length>n ? String(s).slice(0,n-1)+'…' : String(s ?? '');
const since = iso => { const d=(Date.now()-new Date(iso).getTime())/1000; if(d<60)return Math.max(0,Math.floor(d))+'s'; if(d<3600)return Math.floor(d/60)+'m'; if(d<86400)return Math.floor(d/3600)+'h'; return Math.floor(d/86400)+'d'; };
const duration = ms => { let s=Math.max(0,Math.floor(ms/1000)); if(s<60)return s+'s'; if(s<3600)return Math.floor(s/60)+'m '+s%60+'s'; if(s<86400)return Math.floor(s/3600)+'h '+Math.floor((s%3600)/60)+'m'; return Math.floor(s/86400)+'d '+Math.floor((s%86400)/3600)+'h'; };
const bytes = n => {n=Math.max(0,Number(n)||0);if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';if(n<1073741824)return (n/1048576).toFixed(1)+' MB';return (n/1073741824).toFixed(1)+' GB';};
const dt = iso => iso ? new Date(iso).toLocaleString() : '—';
let recentEvents=[];
let sshRecentEvents=[];
let openWebSessionId='';
let openWebSessionData=null;
let httpDrawerPending=0;
let httpDrawerMetaTimer=0;
let sshLiveFeedState=new Map();
let openSSHSessionId='';
let openSSHSessionData=null;
let sshDrawerPending=0;
let sshDrawerMetaTimer=0;
let sshLiveFeedFilter='all';
let sshLiveFeedFollow=true;
let sshHighlights=[];
let sshHighlightNext='';
let sshHighlightFilter='all';
let sshHighlightLoading=false;
let sshHighlightExhausted=false;
let historyRows=[];
let liveMinutes=5;
let selectedTarget="";
let knownTargets=[];
let actorRows=[];
const lazyStep=20;
const lazyLimits={sessions:20,history:20,unknown:20,recentPaths:20,catchAll:20,knownProbes:20,sshSessions:20,sshHistory:20,sshEvents:20,actors:20,bursts:20,intel:20,httpEvents:20};
const lazyLoading={};
const lazyExhausted={};
const regionNames=typeof Intl!=='undefined'&&Intl.DisplayNames?new Intl.DisplayNames([navigator.language||'en'],{type:'region'}):null;
function countryLabel(code){if(!code)return '—';if(code==='LAN')return 'LAN / Private';try{return regionNames?`${regionNames.of(code)} (${code})`:code}catch(e){return code}}

async function api(url){ const r=await fetch(url,{cache:'no-store'}); if(!r.ok) throw new Error(r.status); return r.json(); }
async function loadInfo(){try{const x=await api('/api/info');$('brand').textContent=x.brand;$('version').textContent=`${x.brand} ${x.version}`;$('proxyMode').textContent=x.proxy_mode||'direct';$('geoStatus').textContent=x.geoip_ready?'ready':(x.geo_enrichment?'waiting':'off');if($('botStatus'))$('botStatus').textContent=x.official_bots_enabled?(x.official_bots_cache_ready?'ready':'waiting'):'off';liveMinutes=x.live_session_minutes||5;document.querySelectorAll('.liveWindow').forEach(el=>el.textContent=`${liveMinutes} min`);if($('sshState')){$('sshState').textContent=x.ssh_trap_enabled?`trap enabled · ${x.ssh_trap_addr}`:'optional trap · disabled';$('sshState').classList.toggle('enabled',!!x.ssh_trap_enabled);}}catch(e){}}
async function refresh(){ try {
  const q=selectedTarget?'&target='+encodeURIComponent(selectedTarget):''; const oq=selectedTarget?'?target='+encodeURIComponent(selectedTarget):'';
  const [o,s,e,chartEvents,h,u,rp,c,p,so,ss,sh,se,sf,ao,actors,bursts,intel,health,peers]=await Promise.all([
    api('/api/overview'+oq), api('/api/sessions?limit='+lazyLimits.sessions+q), api('/api/events?limit='+lazyLimits.httpEvents+q), api('/api/events?limit=240'+q),
    api('/api/history?limit='+lazyLimits.history+q), api('/api/unknown-paths?limit='+lazyLimits.unknown), api('/api/recent-paths?limit='+lazyLimits.recentPaths),
    api('/api/catchall-hosts?limit='+lazyLimits.catchAll), api('/api/known-probes?limit='+lazyLimits.knownProbes), api('/api/ssh/overview'),
    api('/api/ssh/sessions?limit='+lazyLimits.sshSessions), api('/api/ssh/history?limit='+lazyLimits.sshHistory), api('/api/ssh/events?limit='+lazyLimits.sshEvents), api('/api/ssh/live-feed?session_limit=12&event_limit=10&left_seconds=10'),
    api('/api/actors/overview'), api('/api/actors?limit='+lazyLimits.actors), api('/api/bursts?limit='+lazyLimits.bursts), api('/api/intelligence?limit='+lazyLimits.intel), api('/api/health'), api('/api/integration/peers')
  ]);
  renderOverview(o); renderSessions(s); recentEvents=e; renderEvents(recentEvents);
  renderChart(chartEvents); historyRows=h; renderHistory(); renderUnknown(u); renderRecentPaths(rp); renderCatchAll(c); renderKnownProbes(p); updateTargets(o.top_targets||[]);
  renderSSHOverview(so); renderSSHSessions(ss); renderSSHHistory(sh); sshRecentEvents=se; renderSSHEvents(se); setSSHLiveFeed(sf); renderActorOverview(ao); renderActors(actors); renderBursts(bursts); renderIntel(intel); renderHealth(health); renderIntegrationPeers(peers);
  noteLoaded('sessions',s.length);noteLoaded('httpEvents',e.length);noteLoaded('history',h.length);noteLoaded('unknown',u.length);noteLoaded('recentPaths',rp.length);noteLoaded('catchAll',(c&&c.hosts||[]).length);noteLoaded('knownProbes',p.length);noteLoaded('sshSessions',ss.length);noteLoaded('sshHistory',sh.length);noteLoaded('sshEvents',se.length);noteLoaded('actors',actors.length);noteLoaded('bursts',bursts.length);noteLoaded('intel',intel.length);
} catch(e) { console.error(e); } }

function renderOverview(o){
  $('hostile').textContent=o.hostile;$('suspicious').textContent=o.suspicious;$('benign').textContent=o.benign;$('requestsToday').textContent=o.requests_today.toLocaleString();$('rps').textContent=o.requests_per_sec.toFixed(1);$('avgDepth').textContent=o.avg_depth.toFixed(1);$('loops').textContent=o.loops_total;
  $('automated').textContent=o.automated;$('human').textContent=o.human;$('unknown').textContent=o.unknown;const t=o.automated+o.human+o.unknown;$('actorTotal').textContent=t;
  const a=t?o.automated/t*100:0,h=t?o.human/t*100:0;$('actorRing').style.background=`conic-gradient(var(--cyan) 0 ${a}%, var(--ok) ${a}% ${a+h}%, #39434a ${a+h}% 100%)`;
  renderBars('topPaths',o.top_paths,30);renderCountryBars(o.top_countries);renderBars('topReferrers',o.top_referrers,30);renderBars('topTargets',o.top_targets,36);
}
function renderBars(id,rows,n=30){const max=Math.max(1,...(rows||[]).map(x=>x.count));$(id).innerHTML=(rows||[]).map(x=>`<div class="bar-row"><label title="${esc(x.name)}">${esc(short(x.name,n))}</label><div class="bar-track"><i style="width:${x.count/max*100}%"></i></div><b>${x.count}</b></div>`).join('')||'<small>No data yet</small>';}
function renderCountryBars(rows){const mapped=(rows||[]).map(x=>({name:countryLabel(x.name),count:x.count}));renderBars('topCountries',mapped,30);}
function viaLabel(s){return s.proxy==='cloudflare'?'CF'+(s.cloudflare_colo?'/'+s.cloudflare_colo:''):s.proxy==='generic'?'PROXY':'DIRECT';}
function riskClass(s){return s.risk_score>=60?'hot':s.risk_score>=30?'mid':'';}
function compactLiveSessions(rows){const groups=new Map();(rows||[]).forEach(s=>{const key=s.ip||s.id;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(s)});const out=[];for(const group of groups.values()){group.sort((a,b)=>new Date(b.last_seen)-new Date(a.last_seen));if(group.length<3){out.push(...group.map(s=>({...s,_groupCount:1})));continue}const latest=group[0],vias=[...new Set(group.map(viaLabel))];out.push({...latest,_groupCount:group.length,_groupIds:group.map(x=>x.id),risk_score:Math.max(...group.map(x=>x.risk_score||0)),automation_score:Math.max(...group.map(x=>x.automation_score||0)),request_count:group.reduce((n,x)=>n+(x.request_count||0),0),depth:Math.max(...group.map(x=>x.depth||0)),loop:Math.max(...group.map(x=>x.loop||0)),actor:group.some(x=>x.actor==='automated')?'automated':latest.actor,_groupVia:vias.join(', ')})}return out.sort((a,b)=>new Date(b.last_seen)-new Date(a.last_seen))}
function renderSessions(rows){const raw=rows||[],shown=compactLiveSessions(raw);$('sessionCount').textContent=`${raw.length}${raw.length>=lazyLimits.sessions?'+':''} active · ${shown.length} row${shown.length===1?'':'s'}`;$('sessionsBody').innerHTML=shown.map(s=>`<tr data-id="${esc(s.id)}" data-ip="${esc(s.ip)}" class="${s._groupCount>1?'session-burst':''}"><td>${since(s.last_seen)}</td><td title="${esc(s.target||'—')}">${esc(short(s.target||'—',28))}</td><td>${esc(s.ip)}${s._groupCount>1?` <span class="burst-count">×${s._groupCount}</span>`:''}</td><td>${esc(s.country||'—')}</td><td title="${esc(s._groupVia||viaLabel(s))}">${esc(short(s._groupVia||viaLabel(s),16))}</td><td class="risk ${riskClass(s)}">${s.risk_score}</td><td>${esc(s.actor)}</td><td>${s.automation_score}%</td><td>${s.request_count}</td><td>${s.depth}</td><td>${s.loop}</td><td class="path" title="${esc(s.current_path)}">${s._groupCount>1?`<span class="muted">${s._groupCount} concurrent · </span>`:''}${esc(short(s.current_path,42))}</td></tr>`).join('') || '<tr class="empty-row"><td colspan="12">No active sessions.</td></tr>';document.querySelectorAll('#sessionsBody tr[data-id]').forEach(tr=>tr.onclick=()=>{const ip=tr.dataset.ip,a=actorRows.find(x=>x.ip===ip);if(tr.classList.contains('session-burst')&&a)openActor(a.id);else openSession(tr.dataset.id)});}

function renderHistory(){const q=($('historySearch')?.value||'').trim().toLowerCase();const rows=q?historyRows.filter(s=>[s.target,s.ip,s.current_path,s.actor,s.classification,s.user_agent,s.country,s.id].some(v=>String(v||'').toLowerCase().includes(q))):historyRows;$('historyCount').textContent=`${rows.length}${rows.length>=lazyLimits.history?'+':''} inactive`;$('historyBody').innerHTML=rows.map(s=>`<tr data-id="${esc(s.id)}"><td>${since(s.last_seen)}</td><td title="${esc(s.target||'—')}">${esc(short(s.target||'—',28))}</td><td>${esc(s.ip)}</td><td>${esc(s.country||'—')}</td><td><span class="badge ${esc(s.classification)}">${esc(s.classification)}</span></td><td>${esc(s.actor)}</td><td>${s.visit_count||1}</td><td>${s.request_count}</td><td>${s.depth}</td><td>${s.loop}</td><td class="path" title="${esc(s.current_path)}">${esc(short(s.current_path,46))}</td></tr>`).join('') || '<tr class="empty-row"><td colspan="11">No matching history.</td></tr>';document.querySelectorAll('#historyBody tr[data-id]').forEach(tr=>tr.onclick=()=>openSession(tr.dataset.id));}
function updateTargets(rows){const values=(rows||[]).map(x=>x.name).filter(x=>x&&x!=="(unknown)");knownTargets=values;const sel=$("targetFilter");const current=selectedTarget;sel.innerHTML='<option value="">All targets</option>'+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');sel.value=current;}
function renderKnownProbes(rows){rows=rows||[];const b=$("knownProbeBody");if(!b)return;const hits=rows.reduce((n,p)=>n+(p.count||0),0);$("knownProbeSummary").textContent=`${hits.toLocaleString()} recognized requests · ${rows.length} signatures · all targets`;b.innerHTML=rows.map(p=>`<tr><td><b>${p.count}</b></td><td class="path" title="${esc(p.name)}">${esc(short(p.name,46))}</td><td title="${esc(p.product||'—')}">${esc(short(p.product||'—',34))}</td><td>${esc(p.cve||'—')}</td><td>${p.hostile_requests||0}</td><td>${p.suspicious_requests||0}</td><td>${since(p.last_seen)}</td></tr>`).join('')||'<tr class="empty-row"><td colspan="7">No known probes yet.</td></tr>';}
function renderUnknown(rows){const b=$("unknownBody");if(!b)return;b.innerHTML=(rows||[]).map(u=>`<tr><td><b>${u.count}</b></td><td>${esc(u.method)}</td><td class="path" title="${esc(u.path)}">${esc(short(u.path,50))}</td><td>${since(u.last_seen)}</td></tr>`).join('')||'<tr class="empty-row"><td colspan="4">No unmapped paths yet.</td></tr>'; }
function renderRecentPaths(rows){const b=$("recentPathsBody");if(!b)return;b.innerHTML=(rows||[]).map(r=>`<tr><td>${since(r.last_seen)}</td><td><b>${r.count}</b></td><td>${esc(r.method)}</td><td class="path" title="${esc(r.path)}">${esc(short(r.path,54))}</td><td><span class="badge ${esc(r.kind==='unmapped'?'suspicious':'benign')}">${esc(r.kind)}</span></td><td>${r.status||'—'}</td><td title="${esc(r.probe_name||'')}">${esc(short(r.probe_name||'—',38))}</td></tr>`).join('')||'<tr class="empty-row"><td colspan="7">No recent paths yet.</td></tr>'; }
function renderIntegrationPeers(rows){rows=rows||[];$('integrationPeerSummary').textContent=`${rows.length} peer${rows.length===1?'':'s'}`;$('integrationPeersBody').innerHTML=rows.map(p=>`<tr class="integration-peer ${esc(p.status)}"><td><b>${esc(p.name)}</b></td><td>${esc(p.source_ip||'—')}</td><td>${esc(p.trust||'—')}</td><td><span class="peer-status ${esc(p.status)}">${esc(p.status)}</span></td><td>${p.last_verified?since(p.last_verified):'never'}</td><td>${Number(p.checks||0).toLocaleString()}</td><td title="${esc(p.last_error||'')}">${Number(p.failures||0).toLocaleString()}</td></tr>`).join('')||'<tr class="empty-row"><td colspan="7">No verified integrations yet.</td></tr>';}
function renderCatchAll(data){const rows=(data&&data.hosts)||[];$('catchAllSummary').textContent=`${(data?.requests_total||0).toLocaleString()} requests · ${data?.hosts_total||0} hosts`;$('catchAllBody').innerHTML=rows.map(h=>`<tr><td><b>${h.requests}</b></td><td class="path" title="${esc(h.host)}">${esc(short(h.host,34))}</td><td>${h.hostile_requests}</td><td>${h.suspicious_requests}</td><td>${since(h.first_seen)}</td><td>${since(h.last_seen)}</td><td>${esc(h.last_integration||'—')}</td></tr>`).join('')||'<tr class="empty-row"><td colspan="7">No trusted catch-all traffic yet.</td></tr>';renderBars('topIntegrations',(data&&data.top_integrations)||[],32);}
function renderEvents(rows){$('events').innerHTML=rows.map(e=>eventHTML(e)).join('');}
function eventHTML(e){const probe=[e.probe_name,e.probe_cve].filter(Boolean).join(" · ");return `<div class="event ${esc(e.classification)}"><time>${new Date(e.at).toLocaleTimeString()}</time><span class="ip" title="Target: ${esc(e.target||'—')}">${esc(short(e.ip,16))}</span><span class="method">${esc(e.method)}</span><span class="e-path" title="${esc(probe||e.path)}">${esc(e.path)}${probe?` <small>· ${esc(probe)}</small>`:''}</span><b class="status">${e.status}</b></div>`}
function renderChart(events){ const svg=$('activityChart'),now=Date.now(),bins=30,span=5*60*1000,arr=Array(bins).fill(0);events.forEach(e=>{const age=now-new Date(e.at).getTime();if(age>=0&&age<span){const idx=bins-1-Math.floor(age/(span/bins));if(idx>=0&&idx<bins)arr[idx]++}});const max=Math.max(1,...arr),w=600,h=150,pts=arr.map((v,i)=>`${i/(bins-1)*w},${h-10-v/max*(h-25)}`).join(' ');svg.innerHTML=`<line class="gridline" x1="0" y1="40" x2="600" y2="40"/><line class="gridline" x1="0" y1="80" x2="600" y2="80"/><line class="gridline" x1="0" y1="120" x2="600" y2="120"/><polygon class="chart-fill" points="0,150 ${pts} 600,150"/><polyline class="chart-line" points="${pts}"/>`;}
function renderActorOverview(o){if(!$('actorActors'))return;$('actorActors').textContent=(o.actors_total||0).toLocaleString();$('actorCross').textContent=(o.cross_protocol||0).toLocaleString();$('actorEngagement').textContent=duration((o.engagement_seconds||0)*1000);$('actorCanaries').textContent=(o.canary_touches||0).toLocaleString();$('actorPayloads').textContent=(o.payload_attempts||0).toLocaleString();renderBars('actorFingerprints',o.top_fingerprints||[],36);}
function renderActors(rows){rows=rows||[];actorRows=rows.slice();$('actorListCount').textContent=`${rows.length}${rows.length>=lazyLimits.actors?'+':''} actors`;$('actorsBody').innerHTML=rows.map(a=>`<tr data-actor-id="${esc(a.id)}"><td>${since(a.last_seen)}</td><td>${esc(a.ip)}</td><td>${esc(a.country||'—')}</td><td>${esc((a.protocols||[]).join(' + ')||'—')}</td><td>${a.http_requests||0}</td><td>${a.ssh_connections||0}</td><td>${a.ssh_commands||0}</td><td>${duration((a.engagement_seconds||0)*1000)}</td><td>${a.depth||0}</td><td>${a.canary_touches||0}</td><td title="${esc((a.fingerprints||[]).join(', '))}">${esc(short((a.fingerprints||[]).join(', ')||'—',42))}</td></tr>`).join('')||'<tr class="empty-row"><td colspan="11">No correlated actors yet.</td></tr>';document.querySelectorAll('#actorsBody tr[data-actor-id]').forEach(tr=>tr.onclick=()=>openActor(tr.dataset.actorId));}

function renderBursts(rows){const b=$("burstsBody");if(!b)return;b.innerHTML=(rows||[]).map(x=>`<tr><td>${since(x.last_seen)}</td><td>${x.sources||0}</td><td>${x.requests||0}</td><td>${esc(x.source_group||'—')}</td><td>${esc(x.fingerprint||'—')}</td><td class="path" title="${esc((x.paths||[]).join(', '))}">${esc(short((x.paths||[]).join(', ')||'—',64))}</td></tr>`).join('')||'<tr class="empty-row"><td colspan="6">No coordinated multi-source bursts retained.</td></tr>';}
function renderIntel(rows){const b=$('intelBody');if(!b)return;b.innerHTML=(rows||[]).map(i=>{const indicator=i.canary?`canary:${i.canary}`:(i.url||i.host||i.filename||i.summary);return `<tr><td>${since(i.at)}</td><td>${esc(i.protocol)}</td><td>${esc(i.kind)}</td><td>${esc(i.tool||i.technique||'—')}</td><td class="path" title="${esc(indicator)}">${esc(short(indicator,48))}</td></tr>`}).join('')||'<tr class="empty-row"><td colspan="5">No payload or canary intelligence yet.</td></tr>';}
function renderHealth(h){if(!$('healthHTTPRejected'))return;$('healthHTTPRejected').textContent=(h.http_rejected||0).toLocaleString();$('healthSSHRejected').textContent=((h.ssh_rejected_global||0)+(h.ssh_rejected_per_ip||0)).toLocaleString();$('healthGuardHits').textContent=((h.ssh_command_budget_hits||0)+(h.ssh_virtual_storage_hits||0)+(h.ssh_recursion_guard_hits||0)).toLocaleString();$('healthStorage').textContent=bytes((h.events_bytes||0)+(h.ssh_events_bytes||0)+(h.intel_events_bytes||0));$('healthMemoryEvents').textContent=((h.http_events_in_memory||0)+(h.ssh_events_in_memory||0)+(h.intel_events_in_memory||0)).toLocaleString();}
async function openActor(id){try{const d=await api('/api/actors/'+encodeURIComponent(id)+'?event_limit=240'),a=d.actor;$('adId').textContent=a.id;$('adIp').textContent=a.ip;$('adCountry').textContent=countryLabel(a.country);$('adProtocols').textContent=(a.protocols||[]).join(' + ')||'—';$('adClass').textContent=a.classification||'—';$('adHTTP').textContent=a.http_requests||0;$('adSSHConn').textContent=a.ssh_connections||0;$('adSSHMedian').textContent=a.ssh_median_revisit_seconds?duration(a.ssh_median_revisit_seconds*1000):'—';$('adSSHJitter').textContent=a.ssh_revisit_jitter_seconds?duration(a.ssh_revisit_jitter_seconds*1000):'—';$('adSSHCmd').textContent=a.ssh_commands||0;$('adEngagement').textContent=duration((a.engagement_seconds||0)*1000);$('adDepth').textContent=a.depth||0;$('adRisk').textContent=(a.risk_score||0)+'/100';$('adCanaries').textContent=a.canary_touches||0;$('adPayloads').textContent=a.payload_attempts||0;$('adFirst').textContent=dt(a.first_seen);$('adLast').textContent=dt(a.last_seen);$('adFingerprints').textContent=(a.fingerprints||[]).join('\n')||'—';$('actorTimeline').innerHTML=(d.timeline||[]).map(x=>`<div class="transcript-step"><small>${new Date(x.at).toLocaleString()} · ${esc((x.protocol||'').toUpperCase())} · ${esc(x.kind||'event')}${x.canary?` · CANARY ${esc(x.canary)}`:''}</small><b>${esc(x.summary||x.path||x.command||'event')}</b>${x.fingerprint?`<span>${esc(x.fingerprint)}</span>`:''}</div>`).join('')||'<small>No timeline retained.</small>';closeAllDrawers();$('actorDrawer').classList.add('open');$('shade').classList.add('open');$('actorDrawer').setAttribute('aria-hidden','false');}catch(e){console.error(e)}}
function renderSSHOverview(o){
  if(!$('sshConnections'))return;
  $('sshConnections').textContent=(o.connections_today||0).toLocaleString();$('sshAuth').textContent=(o.auth_attempts_today||0).toLocaleString();$('sshShells').textContent=(o.shells_today||0).toLocaleString();$('sshCommands').textContent=(o.commands_today||0).toLocaleString();$('sshActive').textContent=o.active_sessions||0;
  renderBars('sshTopUsers',o.top_users||[],28);renderBars('sshTopCommands',o.top_commands||[],28);renderBars('sshTopFamilies',o.top_families||[],32);renderBars('sshTopClients',o.top_clients||[],36);
}
function sshClientLabel(v){return String(v||'—').replace(/^SSH-2\.0-/,'')}
function renderSSHSessions(rows){rows=rows||[];$('sshSessionCount').textContent=`${rows.length}${rows.length>=lazyLimits.sshSessions?'+':''} active`;$('sshSessionsBody').innerHTML=rows.map(s=>`<tr data-ssh-id="${esc(s.id)}"><td>${since(s.last_seen)}</td><td>${esc(s.ip)}</td><td>${esc(s.country||'—')}</td><td>${esc(s.username||'—')}</td><td title="${esc(sshClientLabel(s.client_version))}">${esc(short(sshClientLabel(s.client_version),30))}</td><td>${s.auth_attempts}</td><td>${s.command_count}</td><td>${s.depth}</td><td>${s.loop}</td><td>${esc(short(s.current_dir||'/',25))}</td><td class="path" title="${esc(s.current_command||'')}">${esc(short(s.current_command||'—',42))}</td></tr>`).join('')||'<tr class="empty-row"><td colspan="11">No active SSH trap sessions.</td></tr>';document.querySelectorAll('#sshSessionsBody tr[data-ssh-id]').forEach(tr=>tr.onclick=()=>openSSHSession(tr.dataset.sshId));}
function renderSSHHistory(rows){rows=rows||[];$('sshHistoryCount').textContent=`${rows.length}${rows.length>=lazyLimits.sshHistory?'+':''} sessions`;$('sshHistoryBody').innerHTML=rows.map(s=>`<tr data-ssh-id="${esc(s.id)}"><td>${since(s.last_seen)}</td><td>${esc(s.ip)}</td><td>${esc(s.country||'—')}</td><td>${esc(s.username||'—')}</td><td title="${esc(sshClientLabel(s.client_version))}">${esc(short(sshClientLabel(s.client_version),27))}</td><td>${s.auth_attempts}</td><td>${s.command_count}</td><td>${s.depth}</td><td>${duration((s.duration_seconds||0)*1000)}</td></tr>`).join('')||'<tr class="empty-row"><td colspan="9">No SSH history yet.</td></tr>';document.querySelectorAll('#sshHistoryBody tr[data-ssh-id]').forEach(tr=>tr.onclick=()=>openSSHSession(tr.dataset.sshId));}
function sshEventHTML(e){const main=e.command||e.message||e.type;const meta=[e.username,e.command_family].filter(Boolean).join(' · ');const jump=`data-ssh-session="${esc(e.session_id||'')}" data-ssh-event="${esc(e.id||'')}"`;const ip=e.session_id?`<button type="button" class="ssh-jump ip" ${jump} title="Open session at this event">${esc(short(e.ip,16))}</button>`:`<span class="ip">${esc(short(e.ip,16))}</span>`;const command=e.command&&e.session_id?`<button type="button" class="ssh-jump ssh-command" ${jump} title="Open transcript at this command">${esc(short(main,62))}${meta?` <small>· ${esc(meta)}</small>`:''}</button>`:`<span class="ssh-command" title="${esc(main)}">${esc(short(main,62))}${meta?` <small>· ${esc(meta)}</small>`:''}</span>`;return `<div class="ssh-event"><time>${new Date(e.at).toLocaleTimeString()}</time>${ip}<span class="ssh-type">${esc(e.type)}</span>${command}<b>D${e.depth||0}</b></div>`}
function renderSSHEvents(rows){$('sshEvents').innerHTML=(rows||[]).map(sshEventHTML).join('')||'<small>No SSH activity yet.</small>';}
function sshTranscriptStepHTML(e,s){const title=`${new Date(e.at).toLocaleTimeString()} · ${esc(e.type)}`,attr=`data-ssh-transcript-event="${esc(e.id||'')}"`;if(e.type==='command'||e.type==='exec')return `<div class="transcript-step" ${attr}><small>${title} · ${esc(e.command_family||'other')}</small><b>${esc((e.username||s.username||'user')+'@'+(e.cwd||'/')+' $ '+(e.command||''))}</b>${e.output?`<pre>${esc(e.output)}</pre>`:''}</div>`;return `<div class="transcript-step" ${attr}><small>${title}</small><span>${esc(e.message||e.auth_method||e.type)}</span></div>`;}
function sshSessionStatus(s){if(s&&s.active)return {label:'LIVE',cls:'live'};const t=s&&s.disconnected_at?Date.now()-new Date(s.disconnected_at).getTime():Infinity;if(t<=10000)return {label:`LEFT ${Math.max(0,Math.floor(t/1000))}s`,cls:'left'};return {label:'ENDED',cls:'ended'};}
function updateSSHDrawerStatus(s){const el=$('sdLiveState');if(!el)return;const st=sshSessionStatus(s);el.textContent=st.label;el.className=`ssh-live-state ${st.cls}`;}
function sshDrawerAtBottom(){const d=$('sshDrawer');return d.scrollHeight-d.scrollTop-d.clientHeight<90;}
function followSSHDrawer(){const d=$('sshDrawer');d.scrollTo({top:d.scrollHeight,behavior:'smooth'});sshDrawerPending=0;$('sshNewEvents').hidden=true;}
function appendOpenSSHEvent(e){if(!openSSHSessionId||e.session_id!==openSSHSessionId||!$('sshDrawer').classList.contains('open'))return;const atBottom=sshDrawerAtBottom();if(!openSSHSessionData)return;openSSHSessionData.events=openSSHSessionData.events||[];if(openSSHSessionData.events.some(x=>x.id===e.id))return;openSSHSessionData.events.push(e);$('sshTranscript').insertAdjacentHTML('beforeend',sshTranscriptStepHTML(e,openSSHSessionData.session));const s=openSSHSessionData.session;s.last_seen=e.at;if(e.username)s.username=e.username;if(e.client_version)s.client_version=e.client_version;if(e.cwd)s.current_dir=e.cwd;if(e.depth>s.depth)s.depth=e.depth;if(e.command&&(e.type==='command'||e.type==='exec')){s.current_command=e.command;s.command_count=(s.command_count||0)+1;}if(e.type==='auth')s.auth_attempts=(s.auth_attempts||0)+1;if(e.auth_accepted)s.auth_accepted=true;if(e.type==='connect'||e.type==='shell')s.active=true;if(['disconnect','handshake_error','limit'].includes(e.type)){s.active=false;s.disconnected_at=e.at;s.current_command='';}updateSSHDrawerStatus(s);if(atBottom){requestAnimationFrame(()=>{$('sshDrawer').scrollTop=$('sshDrawer').scrollHeight;});}else{sshDrawerPending++;const b=$('sshNewEvents');b.hidden=false;b.textContent=`${sshDrawerPending} new live event${sshDrawerPending===1?'':'s'} ↓`;}clearTimeout(sshDrawerMetaTimer);sshDrawerMetaTimer=setTimeout(()=>refreshOpenSSHSessionMeta(),450);}
async function refreshOpenSSHSessionMeta(){if(!openSSHSessionId||!$('sshDrawer').classList.contains('open'))return;try{const d=await api('/api/ssh/sessions/'+encodeURIComponent(openSSHSessionId)+'?event_limit=1');if(!openSSHSessionData)return;openSSHSessionData.session=d.session;fillSSHSessionMeta(d.session);}catch(e){}}
function fillSSHSessionMeta(s){$('sdIp').textContent=s.ip;$('sdCountry').textContent=countryLabel(s.country);$('sdUser').textContent=s.username||'—';$('sdClient').textContent=sshClientLabel(s.client_version);$('sdAuth').textContent=s.auth_attempts;$('sdAccepted').textContent=s.auth_accepted?'yes':'no';$('sdShell').textContent=s.shell_opened?'opened':'no';$('sdExec').textContent=s.exec_requests;$('sdCommands').textContent=s.command_count;$('sdCwd').textContent=s.current_dir||'/';$('sdDepth').textContent=s.depth;$('sdLoop').textContent=`${s.loop} / ${s.frustration}`;$('sdFirst').textContent=dt(s.first_seen);$('sdLast').textContent=dt(s.last_seen);$('sdDuration').textContent=duration((s.duration_seconds||0)*1000);$('sdRisk').textContent=(s.risk_score||0)+'/100';updateSSHDrawerStatus(s);}
async function openSSHSession(id,eventId=''){try{const d=await api('/api/ssh/sessions/'+encodeURIComponent(id)+'?event_limit=5000'),s=d.session;openSSHSessionId=id;openSSHSessionData=d;sshDrawerPending=0;$('sshNewEvents').hidden=true;$('sdId').textContent=s.id;fillSSHSessionMeta(s);$('sshExportJSON').href='/api/ssh/sessions/'+encodeURIComponent(id)+'/export.json';$('sshExportTXT').href='/api/ssh/sessions/'+encodeURIComponent(id)+'/export.txt';$('sshTranscript').innerHTML=(d.events||[]).map(e=>sshTranscriptStepHTML(e,s)).join('')||'<small>No transcript events retained.</small>';closeDrawer();const drawer=$('sshDrawer');drawer.classList.add('open');$('shade').classList.add('open');drawer.setAttribute('aria-hidden','false');drawer.scrollTop=0;if(eventId){requestAnimationFrame(()=>requestAnimationFrame(()=>{const target=[...document.querySelectorAll('#sshTranscript [data-ssh-transcript-event]')].find(el=>el.dataset.sshTranscriptEvent===eventId);if(!target)return;target.scrollIntoView({behavior:'smooth',block:'center'});target.classList.add('jump-highlight');setTimeout(()=>target.classList.remove('jump-highlight'),2200);}));}else requestAnimationFrame(()=>{drawer.scrollTop=drawer.scrollHeight;});}catch(e){console.error(e)}}
function setSSHLiveFeed(rows){sshLiveFeedState=new Map();(rows||[]).forEach(x=>sshLiveFeedState.set(x.session.id,{session:x.session,events:(x.events||[]).slice(-10)}));renderSSHLiveFeed();}
function applySSHLiveFeedEvent(e){let x=sshLiveFeedState.get(e.session_id);if(!x)x={session:{id:e.session_id,ip:e.ip,country:e.country||'',username:e.username||'',client_version:e.client_version||'',first_seen:e.at,last_seen:e.at,active:e.type!=='disconnect'&&e.type!=='handshake_error'&&e.type!=='limit',depth:e.depth||0,command_count:0,last_action:e.command||e.message||e.type},events:[]};const ss=x.session;ss.ip=e.ip||ss.ip;ss.country=e.country||ss.country;ss.username=e.username||ss.username;ss.client_version=e.client_version||ss.client_version;ss.last_seen=e.at;ss.depth=Math.max(ss.depth||0,e.depth||0);ss.last_action=e.command||e.message||e.type;if(e.command&&(e.type==='command'||e.type==='exec'))ss.command_count=(ss.command_count||0)+1;if(e.type==='connect'||e.type==='shell')ss.active=true;if(['disconnect','handshake_error','limit'].includes(e.type)){ss.active=false;ss.disconnected_at=e.at;}x.events.push(e);x.events=x.events.slice(-10);sshLiveFeedState.set(e.session_id,x);renderSSHLiveFeed();}
function httpTimelineStepHTML(e){const probe=[e.probe_name,e.probe_cve].filter(Boolean).join(' · ');const meta=[e.method||'GET',e.status||'—',`risk ${e.risk_score||0}`,`D${e.depth||0}`,`L${e.loop||0}`,e.persona||'',probe].filter(Boolean).join(' · ');return `<div class="transcript-step" data-http-timeline-event="${esc(e.id||'')}"><small>${esc(dt(e.at))} · ${esc(meta)}</small><b>${esc(e.path||'/')}</b>${e.message||e.category?`<span>${esc([e.category,e.message].filter(Boolean).join(' · '))}</span>`:''}</div>`;}
function fillWebSessionMeta(s){$('dId').textContent=s.id||'—';$('dIp').textContent=s.ip||'—';$('dProxy').textContent=s.proxy||'direct';$('dIpSource').textContent=s.ip_source||'—';$('dCountry').textContent=countryLabel(s.country);$('dCountrySource').textContent=s.country_source||'—';$('dLanding').textContent=s.first_path||'—';$('dReferrer').textContent=s.last_referrer||s.first_referrer||'—';$('dReferrerHost').textContent=s.referrer_host||'—';$('dTarget').textContent=s.target||'—';$('dRequestHost').textContent=s.request_host||'—';$('dOrigin').textContent=s.origin||'—';$('dLanguage').textContent=s.accept_language||'—';$('dHTTP').textContent=s.http_protocol||'—';$('dIntegration').textContent=s.integration||'—';$('dIntegrationTrust').textContent=s.integration_trust||'—';$('dCatchAll').textContent=s.catch_all?'yes':'no';$('dRay').textContent=s.cloudflare_ray||'—';$('dClass').textContent=s.classification||'—';$('dRisk').textContent=(s.risk_score||0)+'/100';$('dActor').textContent=s.actor||'—';$('dBot').textContent=s.bot_claimed?[s.bot_provider,s.bot_name].filter(Boolean).join(' / ')||'claimed':'none';$('dBotVerified').textContent=s.bot_verified?'verified':'no';$('dAuto').textContent=(s.automation_score||0)+'%';$('dConfidence').textContent=s.confidence||'—';$('dInterval').textContent=s.avg_interval_ms?duration(s.avg_interval_ms):'—';$('dVariance').textContent=s.interval_variance_ms?duration(s.interval_variance_ms):'—';$('dReq').textContent=s.request_count||0;$('dVisits').textContent=s.visit_count||1;$('dFirst').textContent=dt(s.first_seen);$('dLast').textContent=dt(s.last_seen);$('dDepth').textContent=s.depth||0;$('dFrustration').textContent=s.frustration||0;$('dUa').textContent=s.user_agent||'—';$('dAutoBar').style.width=Math.max(0,Math.min(100,s.automation_score||0))+'%';}
function httpDrawerAtBottom(){const d=$('drawer');return d.scrollHeight-d.scrollTop-d.clientHeight<90;}
function followHTTPDrawer(){httpDrawerPending=0;$('httpNewEvents').hidden=true;const d=$('drawer');d.scrollTop=d.scrollHeight;}
function appendOpenWebEvent(e){if(!openWebSessionId||e.session_id!==openWebSessionId||!$('drawer').classList.contains('open'))return;const atBottom=httpDrawerAtBottom();if(!openWebSessionData)return;openWebSessionData.events=openWebSessionData.events||[];if(openWebSessionData.events.some(x=>x.id===e.id))return;openWebSessionData.events.push(e);$('httpTimeline').insertAdjacentHTML('beforeend',httpTimelineStepHTML(e));const ss=openWebSessionData.session;ss.last_seen=e.at;ss.current_path=e.path||ss.current_path;ss.last_method=e.method||ss.last_method;ss.last_status=e.status||ss.last_status;ss.request_count=Math.max(ss.request_count||0,e.session_requests||0);ss.visit_count=Math.max(ss.visit_count||1,e.session_visits||1);ss.depth=Math.max(ss.depth||0,e.depth||0);ss.loop=Math.max(ss.loop||0,e.loop||0);ss.frustration=Math.max(ss.frustration||0,e.frustration||0);ss.risk_score=Math.max(ss.risk_score||0,e.risk_score||0);ss.automation_score=e.automation_score??ss.automation_score;ss.classification=e.classification||ss.classification;ss.actor=e.actor||ss.actor;ss.persona=e.persona||ss.persona;fillWebSessionMeta(ss);if(atBottom){requestAnimationFrame(()=>{$('drawer').scrollTop=$('drawer').scrollHeight;});}else{httpDrawerPending++;const b=$('httpNewEvents');b.hidden=false;b.textContent=`${httpDrawerPending} new live request${httpDrawerPending===1?'':'s'} ↓`;}clearTimeout(httpDrawerMetaTimer);httpDrawerMetaTimer=setTimeout(()=>refreshOpenWebSessionMeta(),450);}
async function refreshOpenWebSessionMeta(){if(!openWebSessionId||!$('drawer').classList.contains('open'))return;try{const d=await api('/api/sessions/'+encodeURIComponent(openWebSessionId)+'?event_limit=1');if(!openWebSessionData)return;openWebSessionData.session=d.session;fillWebSessionMeta(d.session);}catch(e){}}
async function openSession(id){try{const d=await api('/api/sessions/'+encodeURIComponent(id)+'?event_limit=5000'),ss=d.session;openWebSessionId=id;openWebSessionData=d;httpDrawerPending=0;$('httpNewEvents').hidden=true;fillWebSessionMeta(ss);$('httpTimeline').innerHTML=(d.events||[]).map(httpTimelineStepHTML).join('')||'<small>No HTTP events retained for this session.</small>';closeSSHDrawer();closeActorDrawer();const drawer=$('drawer');drawer.classList.add('open');$('shade').classList.add('open');drawer.setAttribute('aria-hidden','false');drawer.scrollTop=0;requestAnimationFrame(()=>{drawer.scrollTop=drawer.scrollHeight;});}catch(e){console.error(e)}}

function renderSSHLiveFeed(){const now=Date.now(),all=[...sshLiveFeedState.values()].filter(x=>x.session.active||(!x.session.disconnected_at?false:now-new Date(x.session.disconnected_at).getTime()<=10000)).sort((a,b)=>new Date(b.session.last_seen)-new Date(a.session.last_seen));const live=all.filter(x=>x.session.active).length,left=all.length-live;const summary=`${live} live · ${left} recently left`;if($('sshLiveFeedSummary'))$('sshLiveFeedSummary').textContent=summary;if($('sshLiveFeedLauncherSummary'))$('sshLiveFeedLauncherSummary').textContent=`${live} live`;if(!$('sshLiveFeed'))return;const items=all.filter(x=>sshLiveFeedFilter==='all'||(sshLiveFeedFilter==='live'&&x.session.active)||(sshLiveFeedFilter==='left'&&!x.session.active));$('sshLiveFeed').innerHTML=items.map(x=>{const s=x.session,st=sshSessionStatus(s);return `<article class="ssh-live-card ${st.cls}" data-ssh-id="${esc(s.id)}"><div class="ssh-live-card-head"><div><b>${esc(s.ip||'—')}</b><span>${esc(s.username||'—')} · ${esc(short(sshClientLabel(s.client_version),28))} · D${s.depth||0}</span></div><span class="ssh-live-state ${st.cls}">${esc(st.label)}</span></div><div class="ssh-live-card-events">${(x.events||[]).map(e=>`<div><time>${new Date(e.at).toLocaleTimeString()}</time><span>${esc((e.type||'').toUpperCase())}</span><b title="${esc(e.command||e.message||e.type)}">${esc(short(e.command||e.message||e.type,70))}</b></div>`).join('')||'<small>No retained activity yet.</small>'}</div><div class="ssh-live-card-foot"><span>${esc(short(s.last_action||'waiting for activity',68))}</span><button type="button">View session</button></div></article>`}).join('')||`<small>No ${sshLiveFeedFilter==='live'?'live':sshLiveFeedFilter==='left'?'recently left':'live SSH'} sessions right now.</small>`;document.querySelectorAll('#sshLiveFeed [data-ssh-id]').forEach(card=>{card.querySelector('button').onclick=()=>openSSHSession(card.dataset.sshId);});if(sshLiveFeedFollow)requestAnimationFrame(()=>document.querySelectorAll('#sshLiveFeed .ssh-live-card-events').forEach(box=>{box.scrollTop=box.scrollHeight;}));}

function renderSSHHighlights(){
  const body=$('sshHighlightsBody');if(!body)return;
  body.innerHTML=sshHighlights.map(h=>`<tr data-ssh-highlight-id="${esc(h.session_id)}"><td>${esc(dt(h.at))}</td><td>${esc(h.ip||'—')}</td><td>${esc(h.country||'—')}</td><td><span class="highlight-rating ${esc(h.rating)}">${esc(h.rating)}</span></td><td><span class="ssh-highlight-score ${esc(h.rating)}">${h.score}/100</span></td><td><span class="ssh-highlight-title" title="${esc(h.title)}">${esc(h.title)}</span><span class="ssh-highlight-reason" title="${esc(h.reason)}">${esc(h.reason)}</span></td><td>${h.commands||0}</td><td>${esc(duration((h.duration_seconds||0)*1000))}</td><td>${h.depth||0}</td></tr>`).join('')||'<tr><td colspan="9"><small>No SSH highlights match this rating yet.</small></td></tr>';
  $('sshHighlightsCount').textContent=`${sshHighlights.length} loaded · authenticated + noteworthy`;
  document.querySelectorAll('#sshHighlightsBody [data-ssh-highlight-id]').forEach(tr=>tr.onclick=()=>openSSHSession(tr.dataset.sshHighlightId));
}
async function loadSSHHighlights(reset=false){
  if(sshHighlightLoading||(!reset&&sshHighlightExhausted))return;
  sshHighlightLoading=true;if($('sshHighlightsLoading'))$('sshHighlightsLoading').hidden=false;
  if(reset){sshHighlights=[];sshHighlightNext='';sshHighlightExhausted=false;renderSSHHighlights();}
  try{let url='/api/ssh/highlights?limit=20&rating='+encodeURIComponent(sshHighlightFilter);if(!reset&&sshHighlightNext)url+='&before='+encodeURIComponent(sshHighlightNext);const page=await api(url),items=page.items||[];const known=new Set(sshHighlights.map(x=>x.session_id));for(const h of items)if(!known.has(h.session_id)){sshHighlights.push(h);known.add(h.session_id)}sshHighlightNext=page.next_before||'';sshHighlightExhausted=!sshHighlightNext||items.length===0;renderSSHHighlights();}catch(e){console.error(e)}finally{sshHighlightLoading=false;if($('sshHighlightsLoading'))$('sshHighlightsLoading').hidden=true;}
}
function setSSHHighlightFilter(filter){sshHighlightFilter=filter;document.querySelectorAll('#sshHighlightFilters [data-highlight-filter]').forEach(b=>b.classList.toggle('active',b.dataset.highlightFilter===filter));loadSSHHighlights(true);}

function openSSHLiveFeed(){const modal=$('sshLiveFeedModal'),backdrop=$('sshLiveFeedBackdrop');if(!modal||!backdrop)return;modal.classList.add('open');backdrop.classList.add('open');modal.setAttribute('aria-hidden','false');backdrop.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');renderSSHLiveFeed();}
function closeSSHLiveFeed(){const modal=$('sshLiveFeedModal'),backdrop=$('sshLiveFeedBackdrop');if(!modal||!backdrop)return;modal.classList.remove('open');backdrop.classList.remove('open');modal.setAttribute('aria-hidden','true');backdrop.setAttribute('aria-hidden','true');if(!$('sshDrawer').classList.contains('open')&&!$('drawer').classList.contains('open')&&!$('actorDrawer').classList.contains('open'))document.body.classList.remove('modal-open');}
function setSSHLiveFeedFilter(filter){sshLiveFeedFilter=filter;document.querySelectorAll('#sshLiveFeedFilters [data-feed-filter]').forEach(b=>b.classList.toggle('active',b.dataset.feedFilter===filter));renderSSHLiveFeed();}
function toggleSSHLiveFollow(){sshLiveFeedFollow=!sshLiveFeedFollow;const b=$('sshLiveFollow');b.classList.toggle('active',sshLiveFeedFollow);b.setAttribute('aria-pressed',sshLiveFeedFollow?'true':'false');b.textContent=sshLiveFeedFollow?'● Live follow':'○ Follow paused';if(sshLiveFeedFollow)renderSSHLiveFeed();}
function syncModalBodyLock(){document.body.classList.toggle('modal-open',$('sshLiveFeedModal')&&$('sshLiveFeedModal').classList.contains('open'));}function closeDrawer(){openWebSessionId='';openWebSessionData=null;httpDrawerPending=0;if($('httpNewEvents'))$('httpNewEvents').hidden=true;$('drawer').classList.remove('open');$('drawer').setAttribute('aria-hidden','true');if(!$('sshDrawer').classList.contains('open')&&!$('actorDrawer').classList.contains('open'))$('shade').classList.remove('open');syncModalBodyLock()}function closeSSHDrawer(){openSSHSessionId='';openSSHSessionData=null;sshDrawerPending=0;$('sshNewEvents').hidden=true;$('sshDrawer').classList.remove('open');$('sshDrawer').setAttribute('aria-hidden','true');if(!$('drawer').classList.contains('open')&&!$('actorDrawer').classList.contains('open'))$('shade').classList.remove('open');syncModalBodyLock()}function closeActorDrawer(){$('actorDrawer').classList.remove('open');$('actorDrawer').setAttribute('aria-hidden','true');if(!$('drawer').classList.contains('open')&&!$('sshDrawer').classList.contains('open'))$('shade').classList.remove('open');syncModalBodyLock()}function closeAllDrawers(){closeDrawer();closeSSHDrawer();closeActorDrawer();$('shade').classList.remove('open');syncModalBodyLock()}$('closeDrawer').onclick=closeDrawer;$('closeSSHDrawer').onclick=closeSSHDrawer;$('closeActorDrawer').onclick=closeActorDrawer;$('shade').onclick=closeAllDrawers;
function connect(){ const es=new EventSource('/api/live/events');es.addEventListener('request',ev=>{try{const e=JSON.parse(ev.data);appendOpenWebEvent(e);if(selectedTarget&&e.target!==selectedTarget)return;const box=$('events');box.insertAdjacentHTML('afterbegin',eventHTML(e));while(box.children.length>lazyLimits.httpEvents)box.lastElementChild.remove();recentEvents.unshift(e);recentEvents=recentEvents.slice(0,Math.max(240,lazyLimits.httpEvents));renderChart(recentEvents);setTimeout(refreshOverviewOnly,120);}catch(err){}});es.onerror=()=>{};}
function connectSSH(){const es=new EventSource('/api/live/ssh');es.addEventListener('ssh',ev=>{try{const e=JSON.parse(ev.data),box=$('sshEvents');box.insertAdjacentHTML('afterbegin',sshEventHTML(e));while(box.children.length>lazyLimits.sshEvents)box.lastElementChild.remove();sshRecentEvents.unshift(e);sshRecentEvents=sshRecentEvents.slice(0,Math.max(160,lazyLimits.sshEvents));applySSHLiveFeedEvent(e);appendOpenSSHEvent(e);setTimeout(refreshSSHOnly,120);}catch(err){}});es.onerror=()=>{};}
async function refreshSSHOnly(){try{const [o,s]=await Promise.all([api('/api/ssh/overview'),api('/api/ssh/sessions?limit='+lazyLimits.sshSessions)]);renderSSHOverview(o);renderSSHSessions(s);}catch(e){}}
async function refreshOverviewOnly(){try{const q=selectedTarget?'&target='+encodeURIComponent(selectedTarget):'';const oq=selectedTarget?'?target='+encodeURIComponent(selectedTarget):'';const [o,s]=await Promise.all([api('/api/overview'+oq),api('/api/sessions?limit='+lazyLimits.sessions+q)]);renderOverview(o);renderSessions(s);}catch(e){}}
function noteLoaded(key,count){lazyExhausted[key]=count<lazyLimits[key];}
function lazyEndpoint(key){
  const q=selectedTarget?'&target='+encodeURIComponent(selectedTarget):'';
  switch(key){
    case 'sessions':return '/api/sessions?limit='+lazyLimits[key]+q;
    case 'history':return '/api/history?limit='+lazyLimits[key]+q;
    case 'unknown':return '/api/unknown-paths?limit='+lazyLimits[key];
    case 'recentPaths':return '/api/recent-paths?limit='+lazyLimits[key];
    case 'catchAll':return '/api/catchall-hosts?limit='+lazyLimits[key];
    case 'knownProbes':return '/api/known-probes?limit='+lazyLimits[key];
    case 'sshSessions':return '/api/ssh/sessions?limit='+lazyLimits[key];
    case 'sshHistory':return '/api/ssh/history?limit='+lazyLimits[key];
    case 'sshEvents':return '/api/ssh/events?limit='+lazyLimits[key];
    case 'actors':return '/api/actors?limit='+lazyLimits[key];
    case 'bursts':return '/api/bursts?limit='+lazyLimits[key];
    case 'intel':return '/api/intelligence?limit='+lazyLimits[key];
    case 'httpEvents':return '/api/events?limit='+lazyLimits[key]+q;
  }
  return '';
}
function applyLazyRows(key,data){
  let count=Array.isArray(data)?data.length:((data&&data.hosts)||[]).length;
  switch(key){
    case 'sessions':renderSessions(data);break;
    case 'history':historyRows=data;renderHistory();break;
    case 'unknown':renderUnknown(data);break;
    case 'recentPaths':renderRecentPaths(data);break;
    case 'catchAll':renderCatchAll(data);break;
    case 'knownProbes':renderKnownProbes(data);break;
    case 'sshSessions':renderSSHSessions(data);break;
    case 'sshHistory':renderSSHHistory(data);break;
    case 'sshEvents':sshRecentEvents=data;renderSSHEvents(data);break;
    case 'actors':renderActors(data);break;
    case 'bursts':renderBursts(data);break;
    case 'intel':renderIntel(data);break;
    case 'httpEvents':recentEvents=data;renderEvents(recentEvents);count=data.length;break;
  }
  return count;
}

async function loadNext(key,box){
  if(lazyLoading[key]||lazyExhausted[key])return;
  const url=lazyEndpoint(key);if(!url)return;
  lazyLoading[key]=true;
  const old=lazyLimits[key],scrollTop=box?box.scrollTop:0;lazyLimits[key]=Math.min(old+lazyStep,1000);
  if(lazyLimits[key]===old){lazyLoading[key]=false;lazyExhausted[key]=true;return;}
  try{const data=await api(lazyEndpoint(key)),count=applyLazyRows(key,data);if(count<lazyLimits[key])lazyExhausted[key]=true;if(box)requestAnimationFrame(()=>{box.scrollTop=scrollTop;});}catch(e){lazyLimits[key]=old;console.error(e)}finally{lazyLoading[key]=false;}
}

function bindLazyScroll(id,key,direct=false){
  const node=$(id);if(!node)return;const box=direct?node:node.closest('.table-wrap');if(!box)return;
  box.addEventListener('scroll',()=>{if(box.scrollTop+box.clientHeight>=box.scrollHeight-48)loadNext(key,box);},{passive:true});
}
function initLazyScroll(){
  [['sessionsBody','sessions'],['historyBody','history'],['actorsBody','actors'],['burstsBody','bursts'],['intelBody','intel'],['sshSessionsBody','sshSessions'],['sshHistoryBody','sshHistory'],['recentPathsBody','recentPaths'],['knownProbeBody','knownProbes'],['unknownBody','unknown'],['catchAllBody','catchAll']].forEach(([id,key])=>bindLazyScroll(id,key));
  bindLazyScroll('events','httpEvents',true);bindLazyScroll('sshEvents','sshEvents',true);
}
$('sshEvents').addEventListener('click',ev=>{const jump=ev.target.closest('.ssh-jump[data-ssh-session]');if(!jump)return;ev.preventDefault();openSSHSession(jump.dataset.sshSession,jump.dataset.sshEvent||'');});
$('sshHighlightsScroll').addEventListener('scroll',()=>{const box=$('sshHighlightsScroll');if(box.scrollTop+box.clientHeight>=box.scrollHeight-64)loadSSHHighlights(false);},{passive:true});$('sshHighlightFilters').addEventListener('click',ev=>{const b=ev.target.closest('[data-highlight-filter]');if(b)setSSHHighlightFilter(b.dataset.highlightFilter);});
$('openSSHLiveFeed').onclick=openSSHLiveFeed;$('closeSSHLiveFeed').onclick=closeSSHLiveFeed;$('sshLiveFeedBackdrop').onclick=closeSSHLiveFeed;$('sshLiveFollow').onclick=toggleSSHLiveFollow;$('sshLiveFeedFilters').addEventListener('click',ev=>{const b=ev.target.closest('[data-feed-filter]');if(b)setSSHLiveFeedFilter(b.dataset.feedFilter);});document.addEventListener('keydown',ev=>{if(ev.key==='Escape'&&$('sshDrawer').classList.contains('open')){closeSSHDrawer();return;}if(ev.key==='Escape'&&$('sshLiveFeedModal').classList.contains('open'))closeSSHLiveFeed();});
$('historySearch').addEventListener('input',renderHistory);$('targetFilter').addEventListener('change',()=>{selectedTarget=$('targetFilter').value;lazyLimits.sessions=20;lazyLimits.history=20;lazyLimits.httpEvents=20;delete lazyExhausted.sessions;delete lazyExhausted.history;delete lazyExhausted.httpEvents;refresh();});
setInterval(()=>{$('clock').textContent=new Date().toLocaleTimeString()},1000);setInterval(refresh,10000);initLazyScroll();loadInfo();refresh();loadSSHHighlights(true);connect();connectSSH();

$('httpNewEvents').onclick=followHTTPDrawer;$('sshNewEvents').onclick=followSSHDrawer;setInterval(()=>{if($('sshLiveFeed'))renderSSHLiveFeed();if(openSSHSessionData)updateSSHDrawerStatus(openSSHSessionData.session);},1000);
